apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: togglemaster
data:
  # Preencha com os outputs do Terraform:
  #   terraform output sqs_queue_url
  #   terraform output redis_primary_endpoint
  SQS_QUEUE_URL: "<SQS_QUEUE_URL>"
  REDIS_ADDR: "<REDIS_PRIMARY_ENDPOINT>:6379"
