# Substitua <EVALUATION_IRSA_ROLE_ARN> pelo output `terraform output evaluation_irsa_role_arn`
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-sa
  namespace: togglemaster
  annotations:
    eks.amazonaws.com/role-arn: "<EVALUATION_IRSA_ROLE_ARN>"
