apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: togglemaster
data:
  # Preencha com os outputs do Terraform:
  #   terraform output sqs_queue_url
  #   terraform output dynamodb_table_name
  SQS_QUEUE_URL: "<SQS_QUEUE_URL>"
  DYNAMODB_TABLE: "ToggleMasterAnalytics"
