# Substitua <ANALYTICS_IRSA_ROLE_ARN> pelo output `terraform output analytics_irsa_role_arn`
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-sa
  namespace: togglemaster
  annotations:
    eks.amazonaws.com/role-arn: "<ANALYTICS_IRSA_ROLE_ARN>"
