name: CI - evaluation

on:
  push:
    branches: [main]
    paths:
      - "services/evaluation/**"
      - ".github/workflows/ci-evaluation.yml"
      - ".github/workflows/reusable-ci-cd.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/evaluation/**"
      - ".github/workflows/ci-evaluation.yml"
      - ".github/workflows/reusable-ci-cd.yml"

jobs:
  ci-cd:
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
      service_name: evaluation
    secrets: inherit
