name: CI - flag

on:
  push:
    branches: [main]
    paths:
      - "services/flag/**"
      - ".github/workflows/ci-flag.yml"
      - ".github/workflows/reusable-ci-cd.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/flag/**"
      - ".github/workflows/ci-flag.yml"
      - ".github/workflows/reusable-ci-cd.yml"

jobs:
  ci-cd:
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
      service_name: flag
    secrets: inherit
